### ISSUE TITLE
Webhook error when using  

### ISSUE THREAD

**Issue by eferraz** [twilio-professional-services/plugin-outbound-cbm#1]
When I Send a message and wait for the customer to reply (the plugging should create a channel, add the message and setup a studio **webhook to handle the inbound**)
When the reply comes in route to the agent that sent the message (or)
When the reply comes in route to any agent

Using any of those gave me a webhook error:

May 30, 2023, 11:04:54 PM
Execution started...
May 30, 2023, 11:04:54 PM
Outbound $(From) -> $(To)
May 30, 2023, 11:04:54 PM
{"accountSid":"AC6ead17fb24e10aaf37436d5a16f41c58","chatServiceSid":"IS874f7314e6684ceda18ec4061d29b638","messagingServiceSid":"MG3756f5cda1e42cf96dc88a6868d985a8","sid":"CH885c5382845045788f9ba58eb697b07b","friendlyName":"Outbound $(From) -> $(To)","uniqueName":"[Object]","attributes":"{"KnownAgentRoutingFlag":true,"KnownAgentWorkerFriendlyName":"ezequiel_2Eferraz"}","state":"active","dateCreated":"2023-05-31T04:04:54.000Z","dateUpdated":"2023-05-31T04:04:54.000Z","timers":"[Object]","...
May 30, 2023, 11:04:54 PM
{"accountSid":"AC6ead17fb24e10aaf37436d5a16f41c58","conversationSid":"CH885c5382845045788f9ba58eb697b07b","sid":"MB6a4528c5a3f84b12bf488a861e3c5d74","identity":"[Object]","attributes":"{}","messagingBinding":"[Object]","roleSid":"RL8a1f7d00d9d24b46993b924c99fb2c5d","dateCreated":"2023-05-31T04:04:54.000Z","dateUpdated":"2023-05-31T04:04:54.000Z","url":"[https://conversations.twilio.com/v1/Conversations/CH885c5382845045788f9ba58eb697b07b/Participants/MB6a4528c5a3f84b12bf488a861e3c5d74","lastRea](https://conversations.twilio.com/v1/Conversations/CH885c5382845045788f9ba58eb697b07b/Participants/MB6a4528c5a3f84b12bf488a861e3c5d74%22,%22lastRea)...
May 30, 2023, 11:04:54 PM
Promise { <pending> }
May 30, 2023, 11:04:55 PM
**UnhandledPromiseRejectionWarning: Unhandled promise rejection: Error: Invalid conversation webhook flow sid at success (/var/task/node_modules/twilio/lib/base/Version.js:79:23) at processTicksAndRejections (internal/process/task_queues.js:95:5)**
May 30, 2023, 11:04:55 PM
Execution ended in 931.79ms using 86MB

**Comment by dahamilton-twilio** [comment]
Hi @eferraz - I just refactored the serverless functions and handling of already active conversations which resulted in some updates around the API request to add the studio webhook.

Can you confirm if you can reproduce the issue with the latest version? thanks

**Comment by dahamilton-twilio** [comment]
@eferraz - one other quick note. A change was also made to use worker sid to handle known agent routing rather than worker name (which had some url encoding issues which weren't apparent when testing using console users!). Letting you know in case you had already setup your TaskRouter workflow as this will need a tweak.

**Comment by eferraz** [comment]
Hi, and thanks..
Do I need to download the project again or just change the function ??? Could you elaborate a little bit more on what is needed on the TaskRouter ?? Thanks again. I am very new on developing

**Comment by dahamilton-twilio** [comment]
I refactored the code a reasonable amount and also split out some of the code from the serverless function as it was getting more complicated so I would recommend starting from scratch.

The change to using the worker sid to route tasks back to the agent that initiated means you will need to change the studio flow and taskrouter where it referenced KnownAgentWorkerFriendlyName -> KnownAgentWorkerSid.

If you follow the steps in the readme for studio and taskrouter you should be all good but feel free to drop a note if you run into any issues.

**Comment by eferraz** [comment]
I will do,, so I think is better to erase the previous function because they have the same name, right?
<img width="1751" alt="Screenshot 2023-06-01 at 4 45 06 PM" src="https://github.com/twilio-professional-services/plugin-outbound-cbm/assets/45804633/e2336879-0001-4a5f-9378-f1167e3b4702">

**Comment by dahamilton-twilio** [comment]
When you deploy serverless again (twilio serverless:deploy) it will take care of making sure it uses the new function

**Comment by eferraz** [comment]
Hi, I tried but I received this error on the console  
<img width="706" alt="Screenshot 2023-06-01 at 5 26 08 PM" src="https://github.com/twilio-professional-services/plugin-outbound-cbm/assets/45804633/915422da-263a-4eb3-8ec1-816ed1c9a4b9">
<img width="910" alt="Screenshot 2023-06-01 at 5 23 36 PM" src="https://github.com/twilio-professional-services/plugin-outbound-cbm/assets/45804633/03e56a8d-9397-406b-be6f-e4d70b0e4367">

**Comment by eferraz** [comment]
Works Nice Thanks,,,,,,, Some advice that i ned to take care to put this in production work very well now

**Comment by dahamilton-twilio** [comment]
Thats great news and thanks for the update @eferraz. I will update the issue as closed.

All of the plugin examples we share are intended as sample code rather than production code so we encourage you to review the code and test to ensure it meets your use case. That said if you do spot any issues we would be happy to hear your feedback.
